<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>错误处理</title>
</head>
<body>
  <script>
    // 1. ReferenceError: 引用的变量不存在
    // console.log(a) // ReferenceError:a is not defined

    // 2. TypeError：数据类型不正确
    let b
    // console.log(b.xxx)// TypeError:Cannot read property 'xxx' of undefined
    let c = {}
    // c.xxx()// TypeError:c.xxx is not a function

    // 3. RangeError：数据值不在其所允许的范围内
    function fn() {
      fn()
    }
    // fn()// RangeError:Maximum call stack size exceeded

    // 4. SyntaxError：语法错误
    // const c = """" // SyntaxError:Unexpected string

    // 错误处理（捕获与抛出）


    // 抛出错误：throw error
    function something() {
      if (Date.now()%2===1) {
        console.log('当前时间为奇数，可以执行任务')
      } else { //如果时间为偶数抛出异常，由调用来处理
        throw new Error('当前时间为偶数，无法执行任务')
      }
    }
    //  捕获错误 try-catch
    try {
      something()
    } catch (error) {
      alert(error.message)
    }

  </script>
</body>
</html>